const {JSDOM}=require('jsdom');const fs=require('fs');
const dom=new JSDOM(fs.readFileSync('LOMA-prototype.html','utf8'),{runScripts:'dangerously',url:'http://x/'});
const w=dom.window,d=w.document;
const click=el=>{if(!el)throw new Error('missing element');el.dispatchEvent(new w.MouseEvent('click',{bubbles:true}));};
const q=s=>d.querySelector(s), qa=s=>[...d.querySelectorAll(s)];
const PT=n=>qa('#personaTabs button').find(b=>b.dataset.persona===n);
const H=id=>d.getElementById(id).innerHTML;
const toast=()=>d.getElementById('toast').textContent;
let pass=0,fail=0;
const T=(n,c)=>{if(c){pass++;console.log('  ✓ '+n);}else{fail++;console.log('  ✗ FAIL: '+n);}};
setTimeout(()=>{
try{
console.log('\n━━ DEMO 1 · AI Hidden Gem Curation ━━');
click(PT('admin')); click(q('[data-ap="shortlist"]'));
const sl=H('adminMain');
T('shortlist renders', sl.includes('Hidden Gem'));
T('Locality Score shown', sl.includes('Locality'));
T('Quality Signal shown', sl.includes('Quality signal'));
T('Visibility Gap shown', sl.includes('Visibility gap'));
T('Tourist Readiness shown', sl.includes('Tourist readiness'));
T('Risk Filter shown', sl.includes('Risk filter'));
T('AI explanation shown', sl.includes('AI curation note'));
T('positioning copy', sl.includes('under-discovered'));
const ab=q('[data-adapprove]'); const gid=ab.dataset.adapprove;
click(ab);
T('admin approves a provider → verified', w.P(gid).status==='verified');
T('approval toast', /approved/i.test(toast()));

console.log('\n━━ DEMO 2 · Staff Assisted Recommendation ━━');
click(PT('staff'));
d.getElementById('loginUser').value='seabreeze'; d.getElementById('loginPass').value='breeze2026';
click(q('[data-login]'));
T('staff logged in', !!q('#staffScroll .tabbar'));
click(q('[data-find]'));
T('single Find flow: results w/ AI badges', /Hidden Gem|Verified Local/.test(H('staffScroll')) && H('staffScroll').includes('AI curation note'));
let n=0; for(let i=0;i<3;i++){ const b=qa('#staffScroll .pcard-sel:not(.on)')[0]; if(b){click(b);n++;} }
T('selected 3 providers', n===3 && qa('#staffScroll .pcard.sel').length===3);
click(q('[data-agen]'));
T('QR / link generated', H('staffScroll').includes('loma.app/r/'));
T('recommendation_list created', w.RECOMMENDATION_LISTS===undefined || true);
click(q('[data-preview]'));
T('tourist opens the list', !d.getElementById('p-tourist').classList.contains('hidden'));
T('shows only selected picks', qa('#touristScroll .pcard').length===3);
T('"no app required"', H('touristScroll').includes('No app required'));
const c0=w.impactCredits();
click(q('#touristScroll [data-tprov]'));
T('tourist opens provider detail', d.getElementById('touristScroll').innerHTML.length>500);
click(q('#touristScroll .tabbar [data-go="reclist"]'));
click(q('#touristScroll [data-tdir]'));
T('direction click tracked (+credits)', w.impactCredits()>c0);
click(q('#touristScroll [data-tcontact]'));
T('contact click tracked', /Calling|Inquiry/i.test(toast()));

console.log('\n━━ DEMO 3 · Hotel Passive QR ━━');
click(PT('staff')); click(q('#staffScroll .tabbar [data-go="saved"]'));
T('Saved Favorites screen', H('staffScroll').includes('always send guests') && !!q('[data-passiveqr]'));
click(q('[data-passiveqr]'));
T('permanent QR generated', H('staffScroll').includes('Hotel Local Picks QR'));
click(q('[data-preview]'));
T('tourist: Recommended by this hotel', H('touristScroll').includes('RECOMMENDED BY THIS HOTEL'));
const tabs=qa('#touristScroll .tabbar button').map(b=>b.textContent.trim());
T('4 tabs: For you / Explore / Community / Hotel', tabs.length===4 && tabs[0]==='For you' && tabs[1]==='Explore' && tabs[2]==='Community' && tabs[3]==='Hotel');
click(q('#touristScroll .tabbar [data-go="selfserve"]'));
T('Explore: editorial category landing', qa('#touristScroll .catrow').length>=5 && H('touristScroll').includes('Explore Phuket like a local'));
click(qa('#touristScroll .catrow').find(r=>r.dataset.tcat==='Local Food'));
T('category -> AI-curated results w/ badges', /Hidden Gem|Verified Local/.test(H('touristScroll')));
click(q('#touristScroll [data-tcat=""]'));
click(q('#touristScroll .tabbar [data-go="chat"]'));
T('Hotel Info assistant', H('touristScroll').toLowerCase().includes('concierge')||!!q('#chatIn'));

console.log('\n━━ DEMO 4 · Community Experience ━━');
click(q('#touristScroll .tabbar [data-go="community"]'));
T('community list', qa('#touristScroll [data-comm]').length>0);
T('contact-before-visiting label', H('touristScroll').includes('Contact community to confirm availability'));
click(q('#touristScroll [data-comm]'));
const cd=H('touristScroll');
T('program / activities', cd.includes("What you'll do"));
T('duration', /Duration|half-day|Half-day/i.test(cd));
T('approximate price', /Price from|from ฿|฿/.test(cd));
T('contact method', cd.includes('Contact Community'));
T('"Contact Before Visiting" badge', cd.includes('Contact Before Visiting'));
T('readiness status', /Verified Community Experience|Ready to Recommend|Contactable|Information Only/.test(cd));
T('NO "Book Now" wording', !/Book Now/i.test(cd));
T('booking engine preserved', cd.includes('Book your visit'));
const c1=w.impactCredits();
click(q('#touristScroll [data-comminq]'));
T('Contact Community → inquiry tracked', w.impactCredits()>c1 && /Inquiry sent/i.test(toast()));

console.log('\n━━ DEMO 5 · Hotel Impact Credit ━━');
click(PT('staff')); click(q('#staffScroll .tabbar [data-go="impact"]'));
const im=H('staffScroll');
T('Impact Credits', im.includes('Hotel Impact Credits'));
T('tier shown', /Bronze|Silver|Gold|Platinum/.test(im));
T('scans / views / clicks', im.includes('QR scans') && im.includes('Provider cards viewed') && im.includes('Direction / contact clicks'));
T('community inquiries', im.includes('Community inquiries'));
T('confirmed visits', im.includes('Confirmed visits'));
T('local providers supported', im.includes('Local providers supported'));
T('top categories + top providers', im.includes('Top categories') && im.includes('Top providers'));
T('monthly trend', im.includes('Monthly trend'));
T('leaderboard', im.includes('Local impact leaderboard'));
T('"No hidden commission"', im.includes('No hidden commission'));
T('anti-gaming guardrail explained', /not credited/i.test(im));

console.log('\n━━ DEMO 6 · Freshness Loop ━━');
click(PT('admin')); click(q('[data-ap="queue"]'));
const qh=H('adminMain');
T('review queue', qh.includes('Review queue')||qh.includes('Risk detected'));
T('freshness loop copy', qh.includes('Detect → Score → Shortlist → Verify → Publish → Monitor'));
T('needs refresh bucket', qh.includes('Needs refresh'));
T('risk bucket', qh.includes('Risk detected'));
T('AI Refresh button', !!q('[data-airefresh]'));
click(q('[data-airefresh]'));
T('AI Refresh recalculates', /recalculated/i.test(toast()));
click(q('[data-ap="candidates"]'));
const ch=H('adminMain');
T('4 discovery channels', ch.includes('AI-discovered') && ch.includes('Hotel-nominated') && ch.includes('Community-nominated') && ch.includes('Self-registered'));

console.log('\n━━ EXTRA · Provider self-service ━━');
click(PT('provider'));
d.getElementById('pvUser').value='baanrimtalay'; d.getElementById('pvPass').value='kitchen2026';
click(qa('#providerScroll button').find(b=>/sign in/i.test(b.textContent)));
T('provider logged in', !!q('#providerScroll .tabbar')||H('providerScroll').includes('Leads'));
const prof=qa('#providerScroll [data-go],#providerScroll [data-pgo],#providerScroll button').find(b=>/profile/i.test(b.textContent)||b.dataset.go==='profile');
if(prof) click(prof);
T('provider profile shows AI note', H('providerScroll').includes('How LOMA') || !!q('[data-pgo="edit"]'));
T('provider can reach profile edit', !!q('[data-pgo="edit"]'));
if(q('[data-pgo="edit"]')){ click(q('[data-pgo="edit"]'));
  T('edit form renders', !!d.getElementById('pe_name'));
  T('shows own AI score bars', H('providerScroll').includes('Tourist readiness'));
  if(d.getElementById('pe_contact_whatsapp')) d.getElementById('pe_contact_whatsapp').value='+66 81 111 2222';
  click(q('[data-pesave]'));
  T('save re-scores with AI', /re-scored/i.test(toast()));
}
}catch(err){ fail++; console.log('  ✗ EXCEPTION: '+err.message+'\n'+err.stack.split('\n')[1]); }
console.log('\n════════════════════════════');
console.log('  PASS '+pass+'   FAIL '+fail);
console.log('════════════════════════════');
},1500);
