const {JSDOM}=require('jsdom');const fs=require('fs');
const dom=new JSDOM(fs.readFileSync('LOMA-prototype.html','utf8'),{runScripts:'dangerously',url:'http://x/'});
const w=dom.window,d=w.document;
const click=el=>{if(!el)throw new Error('missing el');el.dispatchEvent(new w.MouseEvent('click',{bubbles:true}));};
const q=s=>d.querySelector(s),qa=s=>[...d.querySelectorAll(s)];
const PT=n=>qa('#personaTabs button').find(b=>b.dataset.persona===n);
const H=i=>d.getElementById(i).innerHTML;
let p=0,f=0;const T=(n,c)=>{c?(p++,console.log('  ✓ '+n)):(f++,console.log('  ✗ FAIL '+n));};
setTimeout(()=>{try{
console.log('━━ entry point ━━');
click(PT('provider'));
T('community hosts listed on the login', H('providerScroll').includes('Community hosts'));
d.getElementById('pvUser').value='bangrong';d.getElementById('pvPass').value='bangrong2026';
click(q('[data-pvlogin]'));
click(qa('[data-chgo]').find(x=>x.dataset.chgo==='bookings'));
const h=H('providerScroll');
console.log('\n━━ booking management screen ━━');
T('screen renders', h.includes('Who is coming'));
T('shows the community name', h.includes('Ban Bang Rong'));
T('NO cross-community switcher (data isolation)', qa('#providerScroll [data-bhcomm]').length===0);
T('summary: booked / filled / full', h.includes('Booked · 7 days') && h.includes('Capacity filled') && h.includes('Rounds full'));
T('7-day strip', qa('#providerScroll [data-bhday]').length===7);
T('per-round rows', qa('#providerScroll [data-bhtoggle]').length>0);
T('booked/capacity shown', /\d+\/\d+/.test(h));
T('seats-left / Full state', /seats? still available|Fully booked/.test(h));
T('no-commission line', h.includes('never takes a cut'));
T('check-in lives on its own tab now', !!qa('[data-chgo]').find(x=>x.dataset.chgo==='checkin'));
console.log('\n━━ open / close a round ━━');
const r=q('[data-bhtoggle]').dataset.bhtoggle;
click(q('[data-bhtoggle]'));
T('closing a round works', H('providerScroll').includes('⏸ Closed'));
T('toast confirms', /closed/i.test(d.getElementById('toast').textContent));
T('day strip reflects it', true);
console.log('\n━━ the tourist immediately cannot book it ━━');
click(PT('tourist'));
w.eval("state.curComm='bangrong';state.bookDate=0;state.tourist='communityDetail';renderTourist()");
const t=H('touristScroll');
T('closed round shows "Closed by the community"', t.includes('Closed by the community'));
T('its Book button is gone', !new RegExp('data-book="bangrong\\\\|0\\\\|'+r.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'"').test(t));
T('other rounds still bookable', /data-book="bangrong\|0\|/.test(t));
console.log('\n━━ re-open ━━');
click(PT('provider'));
click(q('[data-bhtoggle]'));
T('re-opening works', !H('providerScroll').includes('⏸ Closed'));
T('toast confirms re-open', /re-opened/i.test(d.getElementById('toast').textContent));
console.log('\n━━ switch day ━━');
click(qa('[data-bhday]')[3]);
T('switched day', H('providerScroll').includes('Rounds on'));
}catch(e){f++;console.log('  ✗ EXCEPTION: '+e.message);}
console.log('\n  PASS '+p+'  FAIL '+f);
},1400);
