const {JSDOM}=require('jsdom');const fs=require('fs');
const dom=new JSDOM(fs.readFileSync('LOMA-prototype.html','utf8'),{runScripts:'dangerously',url:'http://x/'});
const w=dom.window,d=w.document;
const click=el=>{if(!el)throw new Error('missing el');el.dispatchEvent(new w.MouseEvent('click',{bubbles:true}));};
const q=s=>d.querySelector(s),qa=s=>[...d.querySelectorAll(s)];
const PT=n=>qa('#personaTabs button').find(b=>b.dataset.persona===n);
const H=()=>d.getElementById('providerScroll').innerHTML;
let p=0,f=0;const T=(n,c)=>{c?(p++,console.log('  ✓ '+n)):(f++,console.log('  ✗ FAIL '+n));};
setTimeout(()=>{try{
// a tourist books first, so there is something to manage
click(PT('tourist'));
w.eval("state.curComm='bangrong';state.bookDate=0;state.bookGuests=3;state.tourist='communityDetail';renderTourist()");
click(q('#touristScroll [data-book]'));
click(PT('provider'));
d.getElementById('pvUser').value='bangrong';d.getElementById('pvPass').value='bangrong2026';
click(q('[data-pvlogin]'));
console.log('━━ community portal now has 5 tabs, like the business portal ━━');
const tabs=qa('#providerScroll .tabbar button').map(b=>b.textContent.trim());
T('5 tabs', tabs.length===5);
T('Home / Bookings / Check-in / Feedback / Profile', tabs.join('/')==='Home/Bookings/Check-in/Feedback/Profile');
T('dark navy tabbar (same theme)', !!q('#providerScroll .tabbar.dk'));
T('appbar with LOMA + community name', H().includes('loma-navy.png') && H().includes('Ban Bang Rong'));
console.log('\n━━ HOME ━━');
T('serif editorial header', H().includes('Hotels are sending'));
T('booked / checked-in / fill / full tiles', H().includes('Guests booked') && H().includes('Guests checked in') && H().includes('Capacity filled'));
T('income via LOMA (฿0 taken)', H().includes('Income via LOMA') && H().includes('LOMA takes ฿0'));
T('readiness spec sheet', H().includes('Your readiness') && H().includes('Group size'));
T('who recommends you', H().includes('Who recommends you') && H().includes('no commission taken'));
T('alert: guests awaiting check-in', H().includes('awaiting check-in'));
console.log('\n━━ BOOKINGS ━━');
click(qa('[data-chgo]').find(b=>b.dataset.chgo==='bookings'));
T('rounds + capacity bars', H().includes('Rounds on') && /\d+\/\d+/.test(H()));
T('7-day strip', qa('[data-bhday]').length===7);
T('open/close toggle', qa('[data-bhtoggle]').length>0);
console.log('\n━━ CHECK-IN ━━');
click(qa('[data-chgo]').find(b=>b.dataset.chgo==='checkin'));
T('scan QR button', !!q('[data-commscan]'));
T('"a booking is not a visit yet"', H().includes('A booking is not'));
T('guest row + check-in button', !!q('[data-checkin]'));
const before=w.eval('econTotals().exact');
click(q('[data-checkin]'));
T('check-in works from the tab', H().includes('✓ Checked in'));
T('income recorded', w.eval('econTotals().exact')>before);
T('income panel updates', H().includes('Income recorded so far'));
console.log('\n━━ FEEDBACK ━━');
click(qa('[data-chgo]').find(b=>b.dataset.chgo==='feedback'));
T('reviews render', H().includes('What guests said'));
T('avg rating', /\d\.\d/.test(H()));
T('only checked-in guests can review', H().includes('Nobody can review a place they never went to'));
console.log('\n━━ PROFILE ━━');
click(qa('[data-chgo]').find(b=>b.dataset.chgo==='profile'));
T('edit form renders', !!d.getElementById('ch_name'));
T('price + contact + transport fields', !!d.getElementById('ch_priceFrom') && !!d.getElementById('ch_contactPerson') && !!d.getElementById('ch_transport'));
T('cannot pay to rank', H().includes('never pay LOMA to appear higher'));
d.getElementById('ch_about').value='We are a mangrove fishing village on the east coast.';
click(q('[data-chsave]'));
T('save works', /Saved/.test(d.getElementById('toast').textContent));
T('edit persists', w.eval("COMM('bangrong').about").includes('mangrove fishing village'));
console.log('\n━━ isolation still holds ━━');
T('no other community visible anywhere', !H().includes('Koh Lone') && !H().includes('Kathu Mining'));
}catch(e){f++;console.log('  ✗ EXCEPTION: '+e.message);}
console.log('\n  PASS '+p+'  FAIL '+f);
},1500);
