const {JSDOM}=require('jsdom');const fs=require('fs');
const dom=new JSDOM(fs.readFileSync('LOMA-prototype.html','utf8'),{runScripts:'dangerously',url:'http://x/'});
const w=dom.window,d=w.document;
const click=el=>{if(!el)throw new Error('missing el');el.dispatchEvent(new w.MouseEvent('click',{bubbles:true}));};
const q=s=>d.querySelector(s),qa=s=>[...d.querySelectorAll(s)];
const PT=n=>qa('#personaTabs button').find(b=>b.dataset.persona===n);
const H=i=>d.getElementById(i).innerHTML;
let p=0,f=0;const T=(n,c)=>{c?(p++,console.log('  ✓ '+n)):(f++,console.log('  ✗ FAIL '+n));};
setTimeout(()=>{try{
console.log('\n━━ Hotel recommends a COMMUNITY ━━');
click(PT('staff'));
d.getElementById('loginUser').value='seabreeze';d.getElementById('loginPass').value='breeze2026';
click(q('[data-login]'));
click(q('[data-find]'));
T('community entry point in Find', !!q('[data-commfind]'));
click(q('[data-commfind]'));
T('communities listed', H('staffScroll').includes('Local communities'));
const commRows=qa('[data-asel]').filter(r=>['bangrong','rawai','oldtown','maikhao','kathu','koh-lone'].includes(r.dataset.asel));
T('6 real communities selectable', commRows.length===6);
T('×1.5 credit hint shown', H('staffScroll').includes('×1.5'));
T('contact-person note', H('staffScroll').includes('before visiting'));
click(q('[data-asel="bangrong"]'));
click(qa('[data-asel]').find(r=>!['bangrong'].includes(r.dataset.asel) && !r.classList.contains('on')));
T('mixed selection (community + SME)', qa('.selrow.on').length===2);
click(q('[data-agen]'));
const qr=H('staffScroll');
T('QR preview shows the community', qr.includes('Ban Bang Rong'));
T('QR preview flags Community Experience', qr.includes('Community Experience'));
click(q('[data-preview]'));
const ts=H('touristScroll');
T('tourist sees the community card', ts.includes('Ban Bang Rong'));
T('"contact X to confirm" on the card', /contact .*to confirm availability/i.test(ts));
T('Contact Community button', !!q('#touristScroll [data-comminq]'));
T('See programme & rounds button', ts.includes('See programme'));
const c0=w.eval('impactCredits()');
click(q('#touristScroll [data-comminq]'));
T('inquiry tracked +credits (x1.5)', w.eval('impactCredits()')>c0);
click(q('#touristScroll [data-comm]'));
const cd=H('touristScroll');
T('→ deep-links into FULL community page', cd.includes("What you'll do") && cd.includes('Book your visit'));
T('shows it was hotel-picked', cd.includes('Your hosts picked this community'));
T('programme + rounds + contact present', cd.includes('Programs & prices')||cd.includes('Book your visit'));
T('back goes to the recommendation list', !!qa('#touristScroll .back,[data-go="reclist"]').length);
}catch(e){f++;console.log('  ✗ EXCEPTION: '+e.message);}
console.log('\n  PASS '+p+'  FAIL '+f);
},1400);
