const {JSDOM}=require('jsdom');const fs=require('fs');
const dom=new JSDOM(fs.readFileSync('LOMA-prototype.html','utf8'),{runScripts:'dangerously',url:'http://x/'});
const w=dom.window,d=w.document;
const click=el=>{if(!el)throw new Error('missing');el.dispatchEvent(new w.MouseEvent('click',{bubbles:true}));};
const q=s=>d.querySelector(s),qa=s=>[...d.querySelectorAll(s)];
const PT=n=>qa('#personaTabs button').find(b=>b.dataset.persona===n);
let p=0,f=0;const T=(n,c)=>{c?(p++,console.log('  ✓ '+n)):(f++,console.log('  ✗ FAIL '+n));};
setTimeout(()=>{try{
console.log('━━ valuation without shop input ━━');
console.log('  priceMid("฿150–350 / person") =', w.eval('priceMid({priceText:"฿150–350 / person"})'));
console.log('  priceMid("฿400 / person · half-day") =', w.eval('priceMid({priceText:"฿400 / person · half-day"})'));
T('parses a declared price band', w.eval('priceMid({priceText:"฿150–350 / person"})')===250);
T('parses a single published price', w.eval('priceMid({priceText:"฿400 / person"})')===400);
const t=w.eval('JSON.stringify(econTotals())');
console.log('  totals:', t);
T('econTotals computes', JSON.parse(t).total>=0);
click(PT('admin')); click(q('[data-ap="econ"]'));
const h=d.getElementById('adminMain').innerHTML;
console.log('\n━━ admin: the method is on screen ━━');
T('nav item exists', !!q('[data-ap="econ"]'));
T('headline: never depend on a shop typing a number', h.includes('never depend on a shop typing a number'));
T('3 confidence tiers', h.includes('Exact') && h.includes('Declared') && h.includes('Benchmark'));
T('% needing zero shop cooperation', h.includes('Needs zero shop cooperation'));
T('explicit formula', h.includes('observed action × published or declared price'));
T('explains the optional spend field', h.includes('calibrate the benchmarks'));
T('anti-gaming: one shop lying moves nothing', h.includes('One shop lying moves nothing'));
T('impact never buys ranking', h.includes('impact never buys ranking'));
T('audit trail', h.includes('how it was valued'));
T('labelled Estimated, not measured', h.includes('never presented as measured revenue'));
console.log('\n━━ a booking alone is worth ฿0 — only a CHECK-IN counts ━━');
w.eval("state.myBookings=[{id:'bangrong',dayIdx:0,round:'08:30',pax:4}]");
const tb=JSON.parse(w.eval('JSON.stringify(econTotals())'));
T('booking alone counts ฿0', tb.exact===0 && tb.pendingBookings===1);
w.eval("state.myBookings[0].status='attended'");
const t2=JSON.parse(w.eval('JSON.stringify(econTotals())'));
console.log('  after the host checks 4 pax in:', JSON.stringify(t2));
T('exact tier picks it up once checked in', t2.exact>0 && t2.nx===1);
T('valued at pax x published price', t2.exact===4*w.eval("priceMid({priceText:COMM('bangrong').priceFrom})"));
click(q('[data-ap="econ"]'));
T('audit row shows the method', d.getElementById('adminMain').innerHTML.includes('checked in × ฿'));
console.log('\n━━ provider Confirm screen is honest ━━');
click(PT('provider'));
d.getElementById('pvUser').value='baanrimtalay';d.getElementById('pvPass').value='kitchen2026';
click(qa('#providerScroll button').find(b=>/sign in/i.test(b.textContent)));
w.eval("state.provider='confirm';renderProvider()");
const ph=d.getElementById('providerScroll').innerHTML;
T('says LOMA does NOT use it for impact', ph.includes('does <b>not</b> use this'));
T('says it cannot raise ranking', ph.includes('cannot raise your ranking'));
}catch(e){f++;console.log('  ✗ EXCEPTION: '+e.message);}
console.log('\n  PASS '+p+'  FAIL '+f);
},1400);
