const {JSDOM}=require('jsdom');const fs=require('fs');
const dom=new JSDOM(fs.readFileSync('LOMA-prototype.html','utf8'),{runScripts:'dangerously',url:'http://x/'});
const w=dom.window,d=w.document;
const click=el=>el&&el.dispatchEvent(new w.MouseEvent('click',{bubbles:true}));
const q=s=>d.querySelector(s),qa=s=>[...d.querySelectorAll(s)];
const PT=n=>qa('#personaTabs button').find(b=>b.dataset.persona===n);
let p=0,f=0;const T=(n,c)=>{c?(p++,console.log('  ✓ '+n)):(f++,console.log('  ✗ FAIL '+n));};
setTimeout(()=>{
click(PT('staff'));
d.getElementById('loginUser').value='seabreeze';d.getElementById('loginPass').value='breeze2026';click(q('[data-login]'));
click(q('[data-find]'));
click(q('[data-commfind]'));
console.log('━━ giant-star bug ━━');
const bare=qa('#staffScroll .selrow .ai svg,#staffScroll .selrow .tx svg').filter(s=>!s.getAttribute('width'));
T('no unsized <svg> left in community rows', bare.length===0);
T('spark icons are hard-sized 13px', qa('#staffScroll .selrow svg[width="13"]').length>0);
console.log('\n━━ sticky Generate QR bar ━━');
T('CTA lives in a sticky footstack', !!q('#staffScroll .footstack .stickbar [data-agen]'));
T('footstack is position:sticky', /\.footstack\{position:sticky/.test(fs.readFileSync('LOMA-prototype.html','utf8')));
T('tabbar is INSIDE the footstack (CTA sits above it)', !!q('#staffScroll .footstack .tabbar'));
T('CTA comes before the tabbar in DOM', (()=>{const fsk=q('#staffScroll .footstack');return fsk.firstElementChild.classList.contains('stickbar');})());
T('helper caption when nothing ticked', q('#staffScroll .stickbar .cap').textContent.includes('Tick one or several'));
click(q('#staffScroll [data-asel]'));
T('caption switches after ticking', q('#staffScroll .stickbar .cap').textContent.includes('No hidden commission'));
T('button label counts picks', q('[data-agen]').textContent.includes('(1 pick)'));
console.log('\n━━ Find vs Saved copy ━━');
w.eval("state.staff='home';renderStaff()");

w.eval("state.staff='saved';renderStaff()");
T('Saved screen says "for EVERY guest"', d.getElementById('staffScroll').innerHTML.includes('<u>every</u> guest'));
console.log('\n  PASS '+p+'  FAIL '+f);
},1400);
