const {JSDOM}=require('jsdom');const fs=require('fs');
const dom=new JSDOM(fs.readFileSync('LOMA-prototype.html','utf8'),{runScripts:'dangerously',url:'http://x/'});
const w=dom.window,d=w.document;
const click=el=>{if(!el)throw new Error('missing el');el.dispatchEvent(new w.MouseEvent('click',{bubbles:true}));};
const q=s=>d.querySelector(s),qa=s=>[...d.querySelectorAll(s)];
const PT=n=>qa('#personaTabs button').find(b=>b.dataset.persona===n);
const H=()=>d.getElementById('providerScroll').innerHTML;
const login=(u,p)=>{d.getElementById('pvUser').value=u;d.getElementById('pvPass').value=p;click(q('[data-pvlogin]'));};
let p=0,f=0;const T=(n,c)=>{c?(p++,console.log('  ✓ '+n)):(f++,console.log('  ✗ FAIL '+n));};
setTimeout(()=>{try{
click(PT('provider'));
console.log('━━ each community has its OWN account ━━');
T('6 community accounts exist', w.eval('COMMUNITY_ACCOUNTS.length')===6);
T('listed on the login screen', H().includes('Community hosts') && H().includes('bangrong'));
T('no direct shortcut into booking data', !q('[data-pauth="commBookings"]') || !H().includes('manage my bookings'));
console.log('\n━━ data isolation ━━');
login('bangrong','bangrong2026');
const h1=H();
T('signed in as Ban Bang Rong', h1.includes('Ban Bang Rong'));
T('no community switcher anymore', qa('[data-bhcomm]').length===0);
T('states the scope on screen', h1.includes('only see and manage') && h1.includes('your own'));
T('shows WHO is signed in', h1.includes('Khun Prasit') || h1.includes('bangrong'));
const others=['Rawai Sea Gypsy','Old Town Heritage','Mai Khao','Kathu Mining','Koh Lone'];
T('CANNOT see any other community', others.every(n=>!h1.includes(n)));
console.log('\n━━ sign out → sign in as a different host ━━');
click(q('[data-commout]'));
T('signed out back to login', !!q('[data-pvlogin]'));
login('kohlonecbt','kohlone2026');
const h2=H();
T('now scoped to Koh Lone', h2.includes('Koh Lone'));
T('CANNOT see Ban Bang Rong', !h2.includes('Ban Bang Rong'));
console.log('\n━━ writes are scoped too ━━');
click(qa('[data-chgo]').find(b=>b.dataset.chgo==='bookings'));
const r=q('[data-bhtoggle]').dataset.bhtoggle;
click(q('[data-bhtoggle]'));
const closed=[...w.eval('[...CLOSED_ROUNDS]')];
T('closing a round only touches THIS community', closed.every(k=>k.startsWith('koh-lone|')));
console.log('\n━━ no session → no data ━━');
w.eval("state.commAcct=null;state.provAuthScreen='commBookings';renderProvider()");
T('community portal refuses to render without a session', !H().includes('Hotels are sending') && !!q('[data-pvlogin]'));
}catch(e){f++;console.log('  ✗ EXCEPTION: '+e.message);}
console.log('\n  PASS '+p+'  FAIL '+f);
},1400);
