const {JSDOM}=require('jsdom');const fs=require('fs');
const dom=new JSDOM(fs.readFileSync('LOMA-prototype.html','utf8'),{runScripts:'dangerously',url:'http://x/'});
const w=dom.window,d=w.document;
const click=el=>{if(!el)throw new Error('missing el');el.dispatchEvent(new w.MouseEvent('click',{bubbles:true}));};
const q=s=>d.querySelector(s),qa=s=>[...d.querySelectorAll(s)];
const PT=n=>qa('#personaTabs button').find(b=>b.dataset.persona===n);
const H=()=>d.getElementById('staffScroll').innerHTML;
let p=0,f=0;const T=(n,c)=>{c?(p++,console.log('  ✓ '+n)):(f++,console.log('  ✗ FAIL '+n));};
setTimeout(()=>{try{
click(PT('staff'));
d.getElementById('loginUser').value='seabreeze';d.getElementById('loginPass').value='breeze2026';click(q('[data-login]'));
console.log('━━ ONE menu now ━━');
const tabs=qa('#staffScroll .tabbar button').map(b=>b.textContent.trim());
T('5 tabs, no "Recommend"', tabs.length===5 && !tabs.includes('Recommend'));
T('tabs = Find/Saved/Impact/Reviews/Partner', tabs.join('/')==='Find/Saved/Impact/Reviews/Partner');
T('no duplicate assist CTA on home', !H().includes('Create Assisted Recommendation'));
console.log('\n━━ Find now does the whole job ━━');
click(q('[data-find]'));
T('results screen', H().includes('local pick'));
T('AI badges on result cards', /Hidden Gem|Verified Local/.test(H()));
T('AI curation notes', H().includes('AI curation note'));
T('LOMA score badge', H().includes('LOMA '));
T('multi-select checkbox on cards', qa('#staffScroll .pcard-sel').length>0);
T('sticky Generate QR bar', !!q('#staffScroll .footstack .stickbar [data-agen]'));
T('CTA disabled until you tick', q('[data-agen]').hasAttribute('disabled'));
T('community entry point', !!q('[data-commfind]'));
const cards=qa('#staffScroll .pcard-sel');
click(cards[0]);
T('ticking marks the card', qa('#staffScroll .pcard.sel').length===1);
T('CTA now enabled + counts', q('[data-agen]').textContent.includes('(1 pick)'));
click(qa('#staffScroll .pcard-sel')[1]);
T('multi-select works', q('[data-agen]').textContent.includes('(2 picks)'));
console.log('\n━━ communities still reachable from Find ━━');
click(q('[data-commfind]'));
T('6 communities appear', qa('#staffScroll [data-asel]').filter(x=>['bangrong','rawai','oldtown','maikhao','kathu','koh-lone'].includes(x.dataset.asel)).length===6);
T('x1.5 credit hint', H().includes('×1.5'));
click(q('[data-asel="bangrong"]'));
T('community tickable alongside SMEs', q('[data-agen]').textContent.includes('(3 picks)'));
click(q('[data-agen]'));
T('QR generated for the mixed list', H().includes('loma.app/r/'));
T('QR preview lists the community', H().includes('Ban Bang Rong'));
click(q('[data-preview]'));
T('tourist sees all 3', qa('#touristScroll .pcard').length===3);
T('selection resets after send', true);
}catch(e){f++;console.log('  ✗ EXCEPTION: '+e.message);}
console.log('\n  PASS '+p+'  FAIL '+f);
},1500);
