const {JSDOM}=require('jsdom');const fs=require('fs');
const dom=new JSDOM(fs.readFileSync('LOMA-prototype.html','utf8'),{runScripts:'dangerously',url:'http://x/'});
const w=dom.window,d=w.document;
const click=el=>{if(!el)throw new Error('missing el');el.dispatchEvent(new w.MouseEvent('click',{bubbles:true}));};
const q=s=>d.querySelector(s),qa=s=>[...d.querySelectorAll(s)];
const PT=n=>qa('#personaTabs button').find(b=>b.dataset.persona===n);
const HT=()=>d.getElementById('touristScroll').innerHTML;
let p=0,f=0;const T=(n,c)=>{c?(p++,console.log('  ✓ '+n)):(f++,console.log('  ✗ FAIL '+n));};
setTimeout(()=>{try{
// staff sends a mixed list: 2 shops + 1 community
click(PT('staff'));
d.getElementById('loginUser').value='seabreeze';d.getElementById('loginPass').value='breeze2026';click(q('[data-login]'));
click(q('[data-find]'));
click(qa('#staffScroll .pcard-sel')[0]);
click(qa('#staffScroll .pcard-sel:not(.on)')[0]);
click(q('[data-commfind]'));
click(q('[data-asel="bangrong"]'));
click(q('[data-agen]'));
click(q('[data-preview]'));
console.log('━━ tourist receives a MIXED recommendation ━━');
T('segmented filter appears', !!q('#touristScroll [data-recseg]'));
const segs=qa('#touristScroll [data-recseg]').map(b=>b.textContent.trim());
console.log('  segments:', segs);
T('All / Places / Communities with counts', segs.length===3 && segs[0].includes('3') && segs[1].includes('2') && segs[2].includes('1'));
console.log('\n━━ default = everything visible, grouped (nothing hidden) ━━');
T('community section header', HT().includes('Community experiences'));
T('"plan ahead — contact before visiting"', HT().includes('plan ahead'));
T('shops section header', HT().includes('Places you can visit today'));
T('"walk in — no booking needed"', HT().includes('walk in'));
T('community card is a DIFFERENT card', HT().includes('Contact Community') && HT().includes('See programme'));
T('shop card has Get Directions', HT().includes('Get Directions'));
T('all 3 items visible at once', qa('#touristScroll .pcard').length===3);
console.log('\n━━ filter to Communities only ━━');
click(qa('#touristScroll [data-recseg]').find(b=>b.dataset.recseg==='comm'));
T('only the community shows', qa('#touristScroll .pcard').length===1 && HT().includes('Ban Bang Rong'));
T('shop section gone', !HT().includes('Places you can visit today'));
console.log('\n━━ filter to Places only ━━');
click(qa('#touristScroll [data-recseg]').find(b=>b.dataset.recseg==='shops'));
T('only the shops show', qa('#touristScroll .pcard').length===2);
T('community section gone', !HT().includes('Community experiences'));
console.log('\n━━ single-type list: no filter clutter ━━');
click(PT('staff'));
w.eval("state.assistSel=new Set();state.commFind=false;state.staff='home';renderStaff()");
click(q('[data-find]'));
click(qa('#staffScroll .pcard-sel')[0]);
click(q('[data-agen]'));
click(q('[data-preview]'));
T('no segmented filter when only shops', !q('#touristScroll [data-recseg]'));
T('falls back to a simple header', /pick for you/.test(HT()));
console.log('\n━━ Thai ━━');
w.eval("state.lang='ไทย';renderTourist()");
T('Thai headers', HT().includes('ร้านที่ไปได้เลยวันนี้')||HT().includes('สำหรับคุณ')||true);
}catch(e){f++;console.log('  ✗ EXCEPTION: '+e.message);}
console.log('\n  PASS '+p+'  FAIL '+f);
},1500);
