const {JSDOM}=require('jsdom');const fs=require('fs');
const dom=new JSDOM(fs.readFileSync('LOMA-prototype.html','utf8'),{runScripts:'dangerously',url:'http://x/'});
const w=dom.window,d=w.document;
const click=el=>{if(!el)throw new Error('missing el');el.dispatchEvent(new w.MouseEvent('click',{bubbles:true}));};
const q=s=>d.querySelector(s),qa=s=>[...d.querySelectorAll(s)];
const PT=n=>qa('#personaTabs button').find(b=>b.dataset.persona==='tourist');
let p=0,f=0;const T=(n,c)=>{c?(p++,console.log('  ✓ '+n)):(f++,console.log('  ✗ FAIL '+n));};
setTimeout(()=>{try{
click(qa('#personaTabs button').find(b=>b.dataset.persona==='tourist'));
click(q('#touristScroll .tabbar [data-go="selfserve"]'));
const h=d.getElementById('touristScroll').innerHTML;
console.log('━━ Explore · editorial landing ━━');
T('serif headline', h.includes('Local experiences,') && h.includes('recommended for you.'));
T('subtitle + rule', h.includes('Explore Phuket like a local.'));
T('LOMA wordmark + menu', h.includes('loma-navy.png'));
T('category rows (not chips)', qa('#touristScroll .catrow').length>=5);
T('row = photo + title + subtitle', h.includes('Authentic flavors') && h.includes('Connect with locals') && h.includes('Handmade with heart'));
T('counts per category', qa('#touristScroll .catrow .n').length>=5);
T('dark navy tabbar', !!q('#touristScroll .tabbar.dk'));
T('uppercase tabs', qa('#touristScroll .tabbar button').map(b=>b.textContent.trim()).join('/')==='For you/Explore/Community/Hotel');
T('AI proof strip retained', h.includes('hidden gems') && h.includes('Nobody paid to appear'));
console.log('\n━━ tap a category → AI results ━━');
click(qa('#touristScroll .catrow').find(r=>r.dataset.tcat==='Local Food'));
const r=d.getElementById('touristScroll').innerHTML;
T('category header', r.includes('Local Food') && r.includes('places near you'));
T('back to all categories', !!q('#touristScroll [data-tcat=""]'));
T('badges + AI notes still there', r.includes('Hidden Gem')||r.includes('Verified Local'));
T('rows render', qa('#touristScroll .prow').length>0);
console.log('\n━━ Community category shows the 6 real communities ━━');
click(q('#touristScroll [data-tcat=""]'));
click(qa('#touristScroll .catrow').find(x=>x.dataset.tcat==='Community Experience'));
const c=d.getElementById('touristScroll').innerHTML;
T('communities listed', c.includes('Ban Bang Rong'));
T('contact-before-visiting badge', c.includes('Contact Before Visiting'));
console.log('\n━━ Thai toggle ━━');
w.eval("state.lang='ไทย';state.tourCat=null;renderTourist()");
const th=d.getElementById('touristScroll').innerHTML;
T('headline translated', th.includes('ประสบการณ์ท้องถิ่น'));
T('categories translated', th.includes('อาหารท้องถิ่น') && th.includes('รสชาติต้นตำรับ'));
}catch(e){f++;console.log('  ✗ EXCEPTION '+e.message);}
console.log('\n  PASS '+p+'  FAIL '+f);
},1400);
