const {JSDOM}=require('jsdom');const fs=require('fs');
const dom=new JSDOM(fs.readFileSync('LOMA-prototype.html','utf8'),{runScripts:'dangerously',url:'http://x/'});
const w=dom.window,d=w.document;
const click=el=>el&&el.dispatchEvent(new w.MouseEvent('click',{bubbles:true}));
const q=s=>d.querySelector(s),qa=s=>[...d.querySelectorAll(s)];
const PT=n=>qa('#personaTabs button').find(b=>b.dataset.persona===n);
let p=0,f=0;const T=(n,c)=>{c?(p++,console.log('  ✓ '+n)):(f++,console.log('  ✗ FAIL '+n));};
setTimeout(()=>{
console.log('━━ theme consistency across all 4 personas ━━');
click(PT('staff'));
d.getElementById('loginUser').value='seabreeze';d.getElementById('loginPass').value='breeze2026';click(q('[data-login]'));
T('STAFF · dark navy tabbar', !!q('#staffScroll .tabbar.dk'));
['saved','impact'].forEach(s=>{ w.eval("state.staff='"+s+"';renderStaff()");
  T('STAFF · '+s+' serif editorial header', !!q('#staffScroll .ed-top h1')); });
click(PT('provider'));
d.getElementById('pvUser').value='baanrimtalay';d.getElementById('pvPass').value='kitchen2026';
click(qa('#providerScroll button').find(b=>/sign in/i.test(b.textContent)));
T('PROVIDER · dark navy tabbar', !!q('#providerScroll .tabbar.dk'));
T('PROVIDER · home serif header', !!q('#providerScroll .ed-top h1'));
w.eval("state.provider='profile';renderProvider()");
T('PROVIDER · profile serif header', !!q('#providerScroll .ed-top h1'));
click(PT('admin'));
w.eval("state.admin='shortlist';renderAdmin()");
const st=w.getComputedStyle? null:null;
T('ADMIN · serif h1 rule present', fs.readFileSync('LOMA-prototype.html','utf8').includes('.amain-head h1{font-family:var(--fd)'));
T('ADMIN · coral zigzag under h1', fs.readFileSync('LOMA-prototype.html','utf8').includes('.amain-head h1::after'));
click(PT('tourist'));
T('TOURIST · dark navy tabbar', !!q('#touristScroll .tabbar.dk'));
click(q('#touristScroll .tabbar [data-go="selfserve"]'));
T('TOURIST · editorial landing', qa('#touristScroll .catrow').length>=5);
console.log('\n  PASS '+p+'  FAIL '+f);
},1400);
